CREATE TABLE `md_peispatientfeeitem` (
     `id` varchar(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT 'ID',
     `id_patientfeeitem` varchar(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '序号',
     `id_patient` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '体检号',
     `id_examfeeitem` varchar(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '体检者收费项目ID',
     `examfeeitem_name` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '收费项目名称:必填/如果基础里面名称没填，此字段填“未命名”，查id未找到此字段填为“未知项”',
     `price` decimal(8,2) DEFAULT NULL COMMENT '原始价格',
     `factprice` decimal(8,2) DEFAULT NULL COMMENT '优惠价格',
     `settleprice` decimal(8,2) DEFAULT NULL COMMENT '结算价格(目前仅用于团检)',
     `f_registered` tinyint(1) DEFAULT NULL COMMENT '已登记',
     `id_doctorreg` varchar(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '登记员ID',
     `doctorreg_r` varchar(16) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '登记员(冗余)',
     `registertime` datetime DEFAULT NULL COMMENT '登记时间',
     `id_patientregistersheet` varchar(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '登记单ID',
     `f_regreturned` tinyint(1) DEFAULT NULL COMMENT '已退登记',
     `f_feecharged` tinyint(1) DEFAULT NULL COMMENT '是否已收费：0.未收费 1.已收费',
     `id_payway` varchar(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '支付方式ID',
     `id_feecharger` varchar(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '收费员ID',
     `feecharger_name_r` varchar(16) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '收费员姓名(冗余)',
     `feechargetime` datetime DEFAULT NULL COMMENT '收费时间',
     `id_feediscounter` varchar(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '打折者ID',
     `f_giveup` tinyint(1) DEFAULT '0' COMMENT '是否弃检：0.未弃检 1.已弃检',
     `f_examinated` tinyint(1) DEFAULT NULL COMMENT '是否已检：0.未检 1.已检',
     `id_patientexamdepart` varchar(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '做检查科室',
     `id_examdoctor` varchar(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '分科检查医师ID',
     `examdoctor_name_r` varchar(16) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '分科检查医师',
     `examinatetime` datetime DEFAULT NULL COMMENT '分科检查时间',
     `f_mark_feereturn` tinyint(1) DEFAULT NULL COMMENT '退费拟退标志',
     `f_work_inner_modify` tinyint(1) DEFAULT NULL COMMENT '修改标志(内部使用)',
     `severedegree` tinyint(1) DEFAULT NULL COMMENT '重症级',


     `batchnumber` int DEFAULT NULL COMMENT '检验: 批次',
     `tubeposition` int DEFAULT NULL COMMENT '检验: 管位',
     `samplenumber` int DEFAULT NULL COMMENT '检验: 样本号',
     `f_labsampled` tinyint(1) DEFAULT NULL COMMENT '检验: 已采样',
     `id_labsampler` varchar(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '采样者ID',
     `labsampler_name_r` varchar(16) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '检验: 采样者',
     `labsampletime` datetime DEFAULT NULL COMMENT '检验: 采样时间',
     `f_labsendtolis` tinyint(1) DEFAULT NULL COMMENT '检验: 已发至LIS',
     `labsendtolistime` datetime DEFAULT NULL COMMENT '检验: 发至LIS时间',
     `f_labrcvdfromlis` tinyint(1) DEFAULT NULL COMMENT '检验: 已自LIS收到结果',
     `labrcvdfromlistime` datetime DEFAULT NULL COMMENT '检验: 收到LIS结果时间',


     `positivesummary` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci COMMENT '阳性小结',
     `interfacemarks` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '接口标志',
     `urlresult` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci COMMENT '结果URL',
     `f_delayed` tinyint(1) DEFAULT NULL COMMENT '迟检  1为迟捡',
     `dt_delayedtill` datetime DEFAULT NULL COMMENT '退费时间',
     `notewhydelayed` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT 'NOTEWHYDELAYED',
     `id_examplace` varchar(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT 'ID_EXAMPLACE',
     `f_transferedhl7` tinyint(1) DEFAULT NULL COMMENT '补检状态 0: 未补检 1：已补检',
     `qty` int DEFAULT NULL COMMENT '序号',
     `feeitemdesc` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '体检者收费项目备注',
     `feeitemsummary` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT 'feeitemsummary',
     `id_typist` varchar(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '寿光jypacs插入中间库标志   1已插入  null未插入',
     `id_examapprovedby` varchar(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT 'ID_EXAMAPPROVEDBY',
     `examapprovedby_name_r` varchar(16) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT 'EXAMAPPROVEDBY_NAME_R',
     `samplenumberfromlis` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT 'SAMPLENUMBERFROMLIS',
     `samplemsgfromlis` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '是否是十周年卡套餐里的项目   1是',
     `receiptsheetnofromhis` varchar(60) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT 'RECEIPTSHEETNOFROMHIS',
     `feeitemrequestno` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT 'FEEITEMREQUESTNO',
     `samplestatus` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '下载标志：0未同步，1已同步,2更新',
     `backupsingleitemcopiesprinted` varchar(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT 'BACKUPSINGLEITEMCOPIESPRINTED',
     `f_feechargedinttrans` tinyint(1) DEFAULT NULL COMMENT '性别',
     `giveupnotelet` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '是否已做  1已做  null或其他未做   在样本录入中录入后会变成已做',
     `create_date` datetime DEFAULT NULL COMMENT '创建时间',
     `sfjx` tinyint(1) DEFAULT NULL COMMENT '0:未加项 1：加项',
     `jxys` varchar(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '加项医师',
     `id_ks` varchar(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '科室ID',
     `count` tinyint(1) DEFAULT NULL COMMENT '数量',
     `createdate` datetime DEFAULT NULL COMMENT '创建时间',
     `modifydate` datetime DEFAULT NULL COMMENT '修改日期',
     `change_item` tinyint(1) DEFAULT '0' COMMENT '换项',
     `is_mintc` tinyint(1) DEFAULT NULL COMMENT '是否是最小套餐：0不是 1是',
     `isbx` tinyint(1) DEFAULT NULL COMMENT '是否备选：0不是 1是',
     `bxcount` tinyint DEFAULT NULL COMMENT '备选数量',
     `endtuiprice` decimal(8,2) DEFAULT NULL COMMENT '退费价格',
     `actualprice` decimal(8,2) DEFAULT NULL COMMENT '实际金额',
     `short_code` int DEFAULT NULL COMMENT '短号体检号',
     `qjr` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '弃检人用户名',
     `bjr` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '补检人用户名',
     `cjr` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '迟检人用户名',
     `qjsj` datetime DEFAULT NULL COMMENT '弃检操作时间',
     `bjsj` datetime DEFAULT NULL COMMENT '补检操作时间',
     `cjsj` datetime DEFAULT NULL COMMENT '迟检操作时间',
     `sfjj` tinyint(1) DEFAULT '0' COMMENT '拒检状态  1拒检   null未拒检',
     `jjr` varchar(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '拒检人用户名',
     `jjsj` datetime DEFAULT NULL COMMENT '拒检时间',
     `jjrqm` varchar(155) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '拒检人签名路径',
     `item_group` int DEFAULT NULL COMMENT 'item_group',
     `adicon_code` varchar(60) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '艾迪康代码',
     `charge_id` varchar(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '收费表ID',
     `trade_no` varchar(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '交易订单号',
     `isconfirm` tinyint(1) DEFAULT NULL COMMENT 'isconfirm',
     PRIMARY KEY (`id`) USING BTREE,
     KEY `IDX_PFEEITEM_TIME` (`feechargetime`) USING BTREE,
     KEY `PEISPATIENTFEEITEME_KS_ID` (`id_patient`,`id_ks`) USING BTREE,
     KEY `PEXAMITEM_CHARGED` (`f_feecharged`) USING BTREE,
     KEY `PEXAMITEM_CODE_CHANGEITEM` (`change_item`) USING BTREE,
     KEY `PEXAMITEM_CODE_GIVEUP` (`f_giveup`) USING BTREE,
     KEY `PEXAMITEM_REGISTERED` (`f_registered`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='体检者收费项目表';