package com.center.medical.center.common.bean.model;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;

/**
 * This class was generated by Apache CXF 3.1.9
 * 2017-01-12T17:38:48.628+08:00
 * Generated source version: 3.1.9
 * 
 */
@WebService(targetNamespace = "http://www.adicon.com.cn/", name = "AdiconWebServiceHttpGet")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface AdiconWebServiceHttpGet {

    /**
     * 获取可下载标本列表。Key＝有效授权码，BeginDateTime＝起始时间， EndDateTime＝结束时间，TypeDateTime＝1=按采集时间统计，2＝按报告时间统计；AgainFlag:1=重新下载已下载过的标本，0＝只下载未下载的标本
     */
    @WebResult(name = "string", targetNamespace = "http://www.adicon.com.cn/", partName = "Body")
    @WebMethod(operationName = "GetReportList")
    public String getReportList(
        @WebParam(partName = "Key", name = "Key", targetNamespace = "http://www.adicon.com.cn/")
        String key,
        @WebParam(partName = "BeginDateTime", name = "BeginDateTime", targetNamespace = "http://www.adicon.com.cn/")
        String beginDateTime,
        @WebParam(partName = "EndDateTime", name = "EndDateTime", targetNamespace = "http://www.adicon.com.cn/")
        String endDateTime,
        @WebParam(partName = "TypeDateTime", name = "TypeDateTime", targetNamespace = "http://www.adicon.com.cn/")
        String typeDateTime,
        @WebParam(partName = "AgainFlag", name = "AgainFlag", targetNamespace = "http://www.adicon.com.cn/")
        String againFlag
    );

    /**
     * 根据客户条码（医院条码）获取标本检测结果或诊断结果。Key＝有效授权码，CustomerBarcode＝客户条码（医院条码）。
     */
    @WebResult(name = "string", targetNamespace = "http://www.adicon.com.cn/", partName = "Body")
    @WebMethod(operationName = "GetReportItemListByCustomerBarocde")
    public String getReportItemListByCustomerBarocde(
        @WebParam(partName = "Key", name = "Key", targetNamespace = "http://www.adicon.com.cn/")
        String key,
        @WebParam(partName = "CustomerBarcode", name = "CustomerBarcode", targetNamespace = "http://www.adicon.com.cn/")
        String customerBarcode,
        @WebParam(partName = "ReportType", name = "ReportType", targetNamespace = "http://www.adicon.com.cn/")
        String reportType
    );

    /**
     * 病理和TCT的P图片，参数说明：barCode=中心条码 bzlb=病种类别,PicType=图片类别：tct or 病理， CurrentRecord=取哪张图片
     */
    @WebResult(name = "string", targetNamespace = "http://www.adicon.com.cn/", partName = "Body")
    @WebMethod(operationName = "GetBLTCTPic")
    public String getBLTCTPic(
        @WebParam(partName = "Key", name = "Key", targetNamespace = "http://www.adicon.com.cn/")
        String key,
        @WebParam(partName = "barCode", name = "barCode", targetNamespace = "http://www.adicon.com.cn/")
        String barCode,
        @WebParam(partName = "bzlbId", name = "bzlbId", targetNamespace = "http://www.adicon.com.cn/")
        String bzlbId,
        @WebParam(partName = "PicType", name = "PicType", targetNamespace = "http://www.adicon.com.cn/")
        String picType,
        @WebParam(partName = "CurrentRecord", name = "CurrentRecord", targetNamespace = "http://www.adicon.com.cn/")
        String currentRecord
    );

    /**
     * 根据医院条码获取标本检测结果或诊断结果。CustomerBarocde＝医院条码
     */
    @WebResult(name = "string", targetNamespace = "http://www.adicon.com.cn/", partName = "Body")
    @WebMethod(operationName = "GetJSONReportItemListByCustomerBarocde")
    public String getJSONReportItemListByCustomerBarocde(
        @WebParam(partName = "CustomerBarocde", name = "CustomerBarocde", targetNamespace = "http://www.adicon.com.cn/")
        String customerBarocde,
        @WebParam(partName = "Key", name = "Key", targetNamespace = "http://www.adicon.com.cn/")
        String key
    );

    /**
     * 状态回调：Key＝有效授权码，CustomerBarcode＝客户条码。
     */
    @WebResult(name = "string", targetNamespace = "http://www.adicon.com.cn/", partName = "Body")
    @WebMethod(operationName = "SetSampleDownFlagByCustomerBarocde")
    public String setSampleDownFlagByCustomerBarocde(
        @WebParam(partName = "Key", name = "Key", targetNamespace = "http://www.adicon.com.cn/")
        String key,
        @WebParam(partName = "CustomerBarcode", name = "CustomerBarcode", targetNamespace = "http://www.adicon.com.cn/")
        String customerBarcode,
        @WebParam(partName = "ReportType", name = "ReportType", targetNamespace = "http://www.adicon.com.cn/")
        String reportType
    );

    /**
     * 通过艾迪康条码获取唐筛标本信息（仅对济南、北京和天津的webservice有效，其他点无效）。Key＝有效授权码，AdiconBarcode=要查询的艾迪康条码号,ReportType=报告类型，请输入：唐筛，以验证你确实要获取唐筛信息
     */
    @WebResult(name = "string", targetNamespace = "http://www.adicon.com.cn/", partName = "Body")
    @WebMethod(operationName = "GetTsscInfoByAdiconBarcode")
    public String getTsscInfoByAdiconBarcode(
        @WebParam(partName = "Key", name = "Key", targetNamespace = "http://www.adicon.com.cn/")
        String key,
        @WebParam(partName = "AdiconBarcode", name = "AdiconBarcode", targetNamespace = "http://www.adicon.com.cn/")
        String adiconBarcode,
        @WebParam(partName = "ReportType", name = "ReportType", targetNamespace = "http://www.adicon.com.cn/")
        String reportType
    );

    /**
     * 根据医院条码判断报告单是否检测完成
     */
    @WebResult(name = "string", targetNamespace = "http://www.adicon.com.cn/", partName = "Body")
    @WebMethod(operationName = "ExistsReportByYYtm")
    public String existsReportByYYtm(
        @WebParam(partName = "Yytm", name = "Yytm", targetNamespace = "http://www.adicon.com.cn/")
        String yytm,
        @WebParam(partName = "Key", name = "Key", targetNamespace = "http://www.adicon.com.cn/")
        String key
    );

    /**
     * 根据艾迪康条码查询。AdiconBarcode＝艾迪康12位条码,获取相关信息病人信息
     */
    @WebResult(name = "string", targetNamespace = "http://www.adicon.com.cn/", partName = "Body")
    @WebMethod(operationName = "GetSearchSample")
    public String getSearchSample(
        @WebParam(partName = "AdiconBarcode", name = "AdiconBarcode", targetNamespace = "http://www.adicon.com.cn/")
        String adiconBarcode,
        @WebParam(partName = "Key", name = "Key", targetNamespace = "http://www.adicon.com.cn/")
        String key
    );

    /**
     * 返回PDF格式的报告单:ID=从GetReportList方法中获取，KEY=有效授权码
     */
    @WebResult(name = "base64Binary", targetNamespace = "http://www.adicon.com.cn/", partName = "Body")
    @WebMethod(operationName = "GetByteReport")
    public byte[] getByteReport(
        @WebParam(partName = "Id", name = "Id", targetNamespace = "http://www.adicon.com.cn/")
        String id,
        @WebParam(partName = "key", name = "key", targetNamespace = "http://www.adicon.com.cn/")
        String key
    );

    /**
     * 获取所有的标本列表。Key＝有效授权码，BeginDateTime＝起始时间， EndDateTime＝结束时间，TypeDateTime＝1=按采集时间统计，2＝按报告时间统计；AgainFlag:2=下载所有标本（包括已下载），0＝只下载未下载的标本
     */
    @WebResult(name = "string", targetNamespace = "http://www.adicon.com.cn/", partName = "Body")
    @WebMethod(operationName = "GetAllSampleList")
    public String getAllSampleList(
        @WebParam(partName = "Key", name = "Key", targetNamespace = "http://www.adicon.com.cn/")
        String key,
        @WebParam(partName = "BeginDateTime", name = "BeginDateTime", targetNamespace = "http://www.adicon.com.cn/")
        String beginDateTime,
        @WebParam(partName = "EndDateTime", name = "EndDateTime", targetNamespace = "http://www.adicon.com.cn/")
        String endDateTime,
        @WebParam(partName = "TypeDateTime", name = "TypeDateTime", targetNamespace = "http://www.adicon.com.cn/")
        String typeDateTime,
        @WebParam(partName = "AgainFlag", name = "AgainFlag", targetNamespace = "http://www.adicon.com.cn/")
        String againFlag
    );

    /**
     * 状态回调：Key＝有效授权码，AdiconBarcode＝艾迪康12位条码。
     */
    @WebResult(name = "string", targetNamespace = "http://www.adicon.com.cn/", partName = "Body")
    @WebMethod(operationName = "SetSampleDownFlagByAdiconBarocde")
    public String setSampleDownFlagByAdiconBarocde(
        @WebParam(partName = "Key", name = "Key", targetNamespace = "http://www.adicon.com.cn/")
        String key,
        @WebParam(partName = "AdiconBarcode", name = "AdiconBarcode", targetNamespace = "http://www.adicon.com.cn/")
        String adiconBarcode,
        @WebParam(partName = "ReportType", name = "ReportType", targetNamespace = "http://www.adicon.com.cn/")
        String reportType
    );

    /**
     * 通过艾迪康条码获取唐筛标本图片信息（仅对济南、北京和天津的webservice有效，其他点无效）。Key＝有效授权码，AdiconBarcode=要查询的艾迪康条码号,ReportType=报告类型，请输入：唐筛，以验证你确实要获取唐筛信息
     */
    @WebResult(name = "base64Binary", targetNamespace = "http://www.adicon.com.cn/", partName = "Body")
    @WebMethod(operationName = "GetTsscPicByAdiconBarcode")
    public byte[] getTsscPicByAdiconBarcode(
        @WebParam(partName = "Key", name = "Key", targetNamespace = "http://www.adicon.com.cn/")
        String key,
        @WebParam(partName = "AdiconBarcode", name = "AdiconBarcode", targetNamespace = "http://www.adicon.com.cn/")
        String adiconBarcode,
        @WebParam(partName = "ReportType", name = "ReportType", targetNamespace = "http://www.adicon.com.cn/")
        String reportType
    );

    /**
     * 根据艾迪康条码查询。AdiconBarcode＝艾迪康12位条码,返回二进制报告单（假如有多张报告单，将合并成一张）
     */
    @WebResult(name = "base64Binary", targetNamespace = "http://www.adicon.com.cn/", partName = "Body")
    @WebMethod(operationName = "GetSearchByteSample")
    public byte[] getSearchByteSample(
        @WebParam(partName = "AdiconBarcode", name = "AdiconBarcode", targetNamespace = "http://www.adicon.com.cn/")
        String adiconBarcode,
        @WebParam(partName = "Key", name = "Key", targetNamespace = "http://www.adicon.com.cn/")
        String key
    );

    /**
     * 根据艾迪康条码查询标本处理过程,AdiconBarcode＝艾迪康12位条码
     */
    @WebResult(name = "string", targetNamespace = "http://www.adicon.com.cn/", partName = "Body")
    @WebMethod(operationName = "GetSampleProcess")
    public String getSampleProcess(
        @WebParam(partName = "AdiconBarcode", name = "AdiconBarcode", targetNamespace = "http://www.adicon.com.cn/")
        String adiconBarcode,
        @WebParam(partName = "Key", name = "Key", targetNamespace = "http://www.adicon.com.cn/")
        String key
    );

    /**
     * 状态回调：Key＝有效授权码，AdiconRepno＝艾迪康生成的内部下载流水号。
     */
    @WebResult(name = "string", targetNamespace = "http://www.adicon.com.cn/", partName = "Body")
    @WebMethod(operationName = "SetSampleDownFlagByByAdiconRepno")
    public String setSampleDownFlagByByAdiconRepno(
        @WebParam(partName = "Key", name = "Key", targetNamespace = "http://www.adicon.com.cn/")
        String key,
        @WebParam(partName = "AdiconRepno", name = "AdiconRepno", targetNamespace = "http://www.adicon.com.cn/")
        String adiconRepno,
        @WebParam(partName = "ReportType", name = "ReportType", targetNamespace = "http://www.adicon.com.cn/")
        String reportType
    );

    /**
     * 根据艾迪康条码获取标本检测结果或诊断结果。AdiconBarcode＝艾迪康12位条码
     */
    @WebResult(name = "string", targetNamespace = "http://www.adicon.com.cn/", partName = "Body")
    @WebMethod(operationName = "GetJSONReportItemListByAdiconBarocde")
    public String getJSONReportItemListByAdiconBarocde(
        @WebParam(partName = "AdiconBarcode", name = "AdiconBarcode", targetNamespace = "http://www.adicon.com.cn/")
        String adiconBarcode,
        @WebParam(partName = "Key", name = "Key", targetNamespace = "http://www.adicon.com.cn/")
        String key
    );

    /**
     * 获取唐筛标本信息（仅对济南、北京和天津的webservice有效，其他点无效）。Key＝有效授权码，CustomerCode=要查询客户的代号（输入All，表示所有客户）,BeginDateTime＝起始时间， EndDateTime＝结束时间，TypeDateTime：1=按采集时间统计，2＝按测定时间统计；ReportType=报告类型，请输入：唐筛，以验证你确实要获取唐筛信息
     */
    @WebResult(name = "string", targetNamespace = "http://www.adicon.com.cn/", partName = "Body")
    @WebMethod(operationName = "GetTsscInfo")
    public String getTsscInfo(
        @WebParam(partName = "Key", name = "Key", targetNamespace = "http://www.adicon.com.cn/")
        String key,
        @WebParam(partName = "CustomerCode", name = "CustomerCode", targetNamespace = "http://www.adicon.com.cn/")
        String customerCode,
        @WebParam(partName = "BeginDateTime", name = "BeginDateTime", targetNamespace = "http://www.adicon.com.cn/")
        String beginDateTime,
        @WebParam(partName = "EndDateTime", name = "EndDateTime", targetNamespace = "http://www.adicon.com.cn/")
        String endDateTime,
        @WebParam(partName = "TypeDateTime", name = "TypeDateTime", targetNamespace = "http://www.adicon.com.cn/")
        String typeDateTime,
        @WebParam(partName = "ReportType", name = "ReportType", targetNamespace = "http://www.adicon.com.cn/")
        String reportType
    );

    /**
     * 根据艾迪康条码判断报告单是否检测完成
     */
    @WebResult(name = "string", targetNamespace = "http://www.adicon.com.cn/", partName = "Body")
    @WebMethod(operationName = "ExistsReport")
    public String existsReport(
        @WebParam(partName = "AdiconBarcode", name = "AdiconBarcode", targetNamespace = "http://www.adicon.com.cn/")
        String adiconBarcode,
        @WebParam(partName = "Key", name = "Key", targetNamespace = "http://www.adicon.com.cn/")
        String key
    );

    /**
     * 返回标本数：Key＝有效授权码
     */
    @WebResult(name = "string", targetNamespace = "http://www.adicon.com.cn/", partName = "Body")
    @WebMethod(operationName = "GetSampleCount")
    public String getSampleCount(
        @WebParam(partName = "key", name = "key", targetNamespace = "http://www.adicon.com.cn/")
        String key,
        @WebParam(partName = "BeginDateTime", name = "BeginDateTime", targetNamespace = "http://www.adicon.com.cn/")
        String beginDateTime,
        @WebParam(partName = "EndDateTime", name = "EndDateTime", targetNamespace = "http://www.adicon.com.cn/")
        String endDateTime
    );

    /**
     * 病理和TCT的P图片，参数说明：barCode=中心条码 finterid=主键,PicType=图片类别：tct or 病理， CurrentRecord=取哪张图片
     */
    @WebResult(name = "string", targetNamespace = "http://www.adicon.com.cn/", partName = "Body")
    @WebMethod(operationName = "GetBLTCTPicByKeyId")
    public String getBLTCTPicByKeyId(
        @WebParam(partName = "Key", name = "Key", targetNamespace = "http://www.adicon.com.cn/")
        String key,
        @WebParam(partName = "barCode", name = "barCode", targetNamespace = "http://www.adicon.com.cn/")
        String barCode,
        @WebParam(partName = "finterid", name = "finterid", targetNamespace = "http://www.adicon.com.cn/")
        String finterid,
        @WebParam(partName = "PicType", name = "PicType", targetNamespace = "http://www.adicon.com.cn/")
        String picType,
        @WebParam(partName = "CurrentRecord", name = "CurrentRecord", targetNamespace = "http://www.adicon.com.cn/")
        String currentRecord
    );

    /**
     * 根据手机号或身份证号获取标本检测结果或诊断结果。OtherCode＝手机号或身份证号
     */
    @WebResult(name = "string", targetNamespace = "http://www.adicon.com.cn/", partName = "Body")
    @WebMethod(operationName = "GetJSONReportItemListByOtherCode")
    public String getJSONReportItemListByOtherCode(
        @WebParam(partName = "OtherCode", name = "OtherCode", targetNamespace = "http://www.adicon.com.cn/")
        String otherCode,
        @WebParam(partName = "Key", name = "Key", targetNamespace = "http://www.adicon.com.cn/")
        String key,
        @WebParam(partName = "datetime", name = "datetime", targetNamespace = "http://www.adicon.com.cn/")
        String datetime
    );

    /**
     * 根据艾迪康条码获取标本检测结果或诊断结果。Key＝有效授权码，AdiconBarcode＝艾迪康12位条码。
     */
    @WebResult(name = "string", targetNamespace = "http://www.adicon.com.cn/", partName = "Body")
    @WebMethod(operationName = "GetReportItemListByAdiconBarocde")
    public String getReportItemListByAdiconBarocde(
        @WebParam(partName = "Key", name = "Key", targetNamespace = "http://www.adicon.com.cn/")
        String key,
        @WebParam(partName = "AdiconBarcode", name = "AdiconBarcode", targetNamespace = "http://www.adicon.com.cn/")
        String adiconBarcode,
        @WebParam(partName = "ReportType", name = "ReportType", targetNamespace = "http://www.adicon.com.cn/")
        String reportType
    );

    /**
     * 根据手机号码或身份证号查询。AdiconBarcode＝手机号码或身份证号,返回二进制报告单（假如有多张报告单，将合并成一张）
     */
    @WebResult(name = "base64Binary", targetNamespace = "http://www.adicon.com.cn/", partName = "Body")
    @WebMethod(operationName = "GetSearchByteSampleByOther")
    public byte[] getSearchByteSampleByOther(
        @WebParam(partName = "AdiconBarcode", name = "AdiconBarcode", targetNamespace = "http://www.adicon.com.cn/")
        String adiconBarcode,
        @WebParam(partName = "Key", name = "Key", targetNamespace = "http://www.adicon.com.cn/")
        String key
    );

    /**
     * 根据艾迪康报告单下载流水号获取标本检测结果。Key＝有效授权码，AdiconRepno＝艾迪康生成的内部下载流水号。此方法可下载单标本的完整报告单。
     */
    @WebResult(name = "string", targetNamespace = "http://www.adicon.com.cn/", partName = "Body")
    @WebMethod(operationName = "GetReportItemListByAdiconRepno")
    public String getReportItemListByAdiconRepno(
        @WebParam(partName = "Key", name = "Key", targetNamespace = "http://www.adicon.com.cn/")
        String key,
        @WebParam(partName = "AdiconRepno", name = "AdiconRepno", targetNamespace = "http://www.adicon.com.cn/")
        String adiconRepno,
        @WebParam(partName = "ReportType", name = "ReportType", targetNamespace = "http://www.adicon.com.cn/")
        String reportType
    );

    /**
     * 用户验证获得授权码
     */
    @WebResult(name = "string", targetNamespace = "http://www.adicon.com.cn/", partName = "Body")
    @WebMethod(operationName = "Login")
    public String login(
        @WebParam(partName = "logid", name = "logid", targetNamespace = "http://www.adicon.com.cn/")
        String logid,
        @WebParam(partName = "password", name = "password", targetNamespace = "http://www.adicon.com.cn/")
        String password
    );
}
