package com.center.medical.center.common.bean.model;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.9
 * 2017-01-12T17:38:48.641+08:00
 * Generated source version: 3.1.9
 * 
 */
@WebService(targetNamespace = "http://www.adicon.com.cn/", name = "AdiconWebServiceSoap")
public interface AdiconWebServiceSoap {

    /**
     * 获取可下载标本列表。Key＝有效授权码，BeginDateTime＝起始时间， EndDateTime＝结束时间，TypeDateTime＝1=按采集时间统计，2＝按报告时间统计；AgainFlag:1=重新下载已下载过的标本，0＝只下载未下载的标本
     */
    @WebResult(name = "GetReportListResult", targetNamespace = "http://www.adicon.com.cn/")
    @RequestWrapper(localName = "GetReportList", targetNamespace = "http://www.adicon.com.cn/", className = "cn.com.adicon.GetReportList")
    @WebMethod(operationName = "GetReportList", action = "http://www.adicon.com.cn/GetReportList")
    @ResponseWrapper(localName = "GetReportListResponse", targetNamespace = "http://www.adicon.com.cn/", className = "cn.com.adicon.GetReportListResponse")
    public String getReportList(
        @WebParam(name = "Key", targetNamespace = "http://www.adicon.com.cn/")
        String key,
        @WebParam(name = "BeginDateTime", targetNamespace = "http://www.adicon.com.cn/")
        String beginDateTime,
        @WebParam(name = "EndDateTime", targetNamespace = "http://www.adicon.com.cn/")
        String endDateTime,
        @WebParam(name = "TypeDateTime", targetNamespace = "http://www.adicon.com.cn/")
        String typeDateTime,
        @WebParam(name = "AgainFlag", targetNamespace = "http://www.adicon.com.cn/")
        String againFlag
    );

    /**
     * 根据客户条码（医院条码）获取标本检测结果或诊断结果。Key＝有效授权码，CustomerBarcode＝客户条码（医院条码）。
     */
    @WebResult(name = "GetReportItemListByCustomerBarocdeResult", targetNamespace = "http://www.adicon.com.cn/")
    @RequestWrapper(localName = "GetReportItemListByCustomerBarocde", targetNamespace = "http://www.adicon.com.cn/", className = "cn.com.adicon.GetReportItemListByCustomerBarocde")
    @WebMethod(operationName = "GetReportItemListByCustomerBarocde", action = "http://www.adicon.com.cn/GetReportItemListByCustomerBarocde")
    @ResponseWrapper(localName = "GetReportItemListByCustomerBarocdeResponse", targetNamespace = "http://www.adicon.com.cn/", className = "cn.com.adicon.GetReportItemListByCustomerBarocdeResponse")
    public String getReportItemListByCustomerBarocde(
        @WebParam(name = "Key", targetNamespace = "http://www.adicon.com.cn/")
        String key,
        @WebParam(name = "CustomerBarcode", targetNamespace = "http://www.adicon.com.cn/")
        String customerBarcode,
        @WebParam(name = "ReportType", targetNamespace = "http://www.adicon.com.cn/")
        String reportType
    );

    /**
     * 病理和TCT的P图片，参数说明：barCode=中心条码 bzlb=病种类别,PicType=图片类别：tct or 病理， CurrentRecord=取哪张图片
     */
    @WebResult(name = "GetBLTCTPicResult", targetNamespace = "http://www.adicon.com.cn/")
    @RequestWrapper(localName = "GetBLTCTPic", targetNamespace = "http://www.adicon.com.cn/", className = "cn.com.adicon.GetBLTCTPic")
    @WebMethod(operationName = "GetBLTCTPic", action = "http://www.adicon.com.cn/GetBLTCTPic")
    @ResponseWrapper(localName = "GetBLTCTPicResponse", targetNamespace = "http://www.adicon.com.cn/", className = "cn.com.adicon.GetBLTCTPicResponse")
    public String getBLTCTPic(
        @WebParam(name = "Key", targetNamespace = "http://www.adicon.com.cn/")
        String key,
        @WebParam(name = "barCode", targetNamespace = "http://www.adicon.com.cn/")
        String barCode,
        @WebParam(name = "bzlbId", targetNamespace = "http://www.adicon.com.cn/")
        String bzlbId,
        @WebParam(name = "PicType", targetNamespace = "http://www.adicon.com.cn/")
        String picType,
        @WebParam(name = "CurrentRecord", targetNamespace = "http://www.adicon.com.cn/")
        int currentRecord
    );

    /**
     * 根据医院条码获取标本检测结果或诊断结果。CustomerBarocde＝医院条码
     */
    @WebResult(name = "GetJSONReportItemListByCustomerBarocdeResult", targetNamespace = "http://www.adicon.com.cn/")
    @RequestWrapper(localName = "GetJSONReportItemListByCustomerBarocde", targetNamespace = "http://www.adicon.com.cn/", className = "cn.com.adicon.GetJSONReportItemListByCustomerBarocde")
    @WebMethod(operationName = "GetJSONReportItemListByCustomerBarocde", action = "http://www.adicon.com.cn/GetJSONReportItemListByCustomerBarocde")
    @ResponseWrapper(localName = "GetJSONReportItemListByCustomerBarocdeResponse", targetNamespace = "http://www.adicon.com.cn/", className = "cn.com.adicon.GetJSONReportItemListByCustomerBarocdeResponse")
    public String getJSONReportItemListByCustomerBarocde(
        @WebParam(name = "CustomerBarocde", targetNamespace = "http://www.adicon.com.cn/")
        String customerBarocde,
        @WebParam(name = "Key", targetNamespace = "http://www.adicon.com.cn/")
        String key
    );

    /**
     * 状态回调：Key＝有效授权码，CustomerBarcode＝客户条码。
     */
    @WebResult(name = "SetSampleDownFlagByCustomerBarocdeResult", targetNamespace = "http://www.adicon.com.cn/")
    @RequestWrapper(localName = "SetSampleDownFlagByCustomerBarocde", targetNamespace = "http://www.adicon.com.cn/", className = "cn.com.adicon.SetSampleDownFlagByCustomerBarocde")
    @WebMethod(operationName = "SetSampleDownFlagByCustomerBarocde", action = "http://www.adicon.com.cn/SetSampleDownFlagByCustomerBarocde")
    @ResponseWrapper(localName = "SetSampleDownFlagByCustomerBarocdeResponse", targetNamespace = "http://www.adicon.com.cn/", className = "cn.com.adicon.SetSampleDownFlagByCustomerBarocdeResponse")
    public String setSampleDownFlagByCustomerBarocde(
        @WebParam(name = "Key", targetNamespace = "http://www.adicon.com.cn/")
        String key,
        @WebParam(name = "CustomerBarcode", targetNamespace = "http://www.adicon.com.cn/")
        String customerBarcode,
        @WebParam(name = "ReportType", targetNamespace = "http://www.adicon.com.cn/")
        String reportType
    );

    /**
     * 通过艾迪康条码获取唐筛标本信息（仅对济南、北京和天津的webservice有效，其他点无效）。Key＝有效授权码，AdiconBarcode=要查询的艾迪康条码号,ReportType=报告类型，请输入：唐筛，以验证你确实要获取唐筛信息
     */
    @WebResult(name = "GetTsscInfoByAdiconBarcodeResult", targetNamespace = "http://www.adicon.com.cn/")
    @RequestWrapper(localName = "GetTsscInfoByAdiconBarcode", targetNamespace = "http://www.adicon.com.cn/", className = "cn.com.adicon.GetTsscInfoByAdiconBarcode")
    @WebMethod(operationName = "GetTsscInfoByAdiconBarcode", action = "http://www.adicon.com.cn/GetTsscInfoByAdiconBarcode")
    @ResponseWrapper(localName = "GetTsscInfoByAdiconBarcodeResponse", targetNamespace = "http://www.adicon.com.cn/", className = "cn.com.adicon.GetTsscInfoByAdiconBarcodeResponse")
    public String getTsscInfoByAdiconBarcode(
        @WebParam(name = "Key", targetNamespace = "http://www.adicon.com.cn/")
        String key,
        @WebParam(name = "AdiconBarcode", targetNamespace = "http://www.adicon.com.cn/")
        String adiconBarcode,
        @WebParam(name = "ReportType", targetNamespace = "http://www.adicon.com.cn/")
        String reportType
    );

    /**
     * 根据医院条码判断报告单是否检测完成
     */
    @WebResult(name = "ExistsReportByYYtmResult", targetNamespace = "http://www.adicon.com.cn/")
    @RequestWrapper(localName = "ExistsReportByYYtm", targetNamespace = "http://www.adicon.com.cn/", className = "cn.com.adicon.ExistsReportByYYtm")
    @WebMethod(operationName = "ExistsReportByYYtm", action = "http://www.adicon.com.cn/ExistsReportByYYtm")
    @ResponseWrapper(localName = "ExistsReportByYYtmResponse", targetNamespace = "http://www.adicon.com.cn/", className = "cn.com.adicon.ExistsReportByYYtmResponse")
    public String existsReportByYYtm(
        @WebParam(name = "Yytm", targetNamespace = "http://www.adicon.com.cn/")
        String yytm,
        @WebParam(name = "Key", targetNamespace = "http://www.adicon.com.cn/")
        String key
    );

    /**
     * 根据艾迪康条码查询。AdiconBarcode＝艾迪康12位条码,获取相关信息病人信息
     */
    @WebResult(name = "GetSearchSampleResult", targetNamespace = "http://www.adicon.com.cn/")
    @RequestWrapper(localName = "GetSearchSample", targetNamespace = "http://www.adicon.com.cn/", className = "cn.com.adicon.GetSearchSample")
    @WebMethod(operationName = "GetSearchSample", action = "http://www.adicon.com.cn/GetSearchSample")
    @ResponseWrapper(localName = "GetSearchSampleResponse", targetNamespace = "http://www.adicon.com.cn/", className = "cn.com.adicon.GetSearchSampleResponse")
    public String getSearchSample(
        @WebParam(name = "AdiconBarcode", targetNamespace = "http://www.adicon.com.cn/")
        String adiconBarcode,
        @WebParam(name = "Key", targetNamespace = "http://www.adicon.com.cn/")
        String key
    );

    /**
     * 返回Jpeg格式的报告单:ID=从GetReportList方法中获取，KEY=有效授权码
     */
    @WebResult(name = "GetByteJpegReportByIdResult", targetNamespace = "http://www.adicon.com.cn/")
    @RequestWrapper(localName = "GetByteJpegReportById", targetNamespace = "http://www.adicon.com.cn/", className = "cn.com.adicon.GetByteJpegReportById")
    @WebMethod(operationName = "GetByteJpegReportById", action = "http://www.adicon.com.cn/GetByteJpegReportById")
    @ResponseWrapper(localName = "GetByteJpegReportByIdResponse", targetNamespace = "http://www.adicon.com.cn/", className = "cn.com.adicon.GetByteJpegReportByIdResponse")
    public byte[] GetByteJpegReportById(
        @WebParam(name = "Id", targetNamespace = "http://www.adicon.com.cn/")
        String id,
        @WebParam(name = "key", targetNamespace = "http://www.adicon.com.cn/")
        String key
    );


    /**
     * 返回PDF格式的报告单:ID=从GetReportList方法中获取，KEY=有效授权码
     */
    @WebResult(name = "GetByteReportResult", targetNamespace = "http://www.adicon.com.cn/")
    @RequestWrapper(localName = "GetByteReport", targetNamespace = "http://www.adicon.com.cn/", className = "cn.com.adicon.GetByteReport")
    @WebMethod(operationName = "GetByteReport", action = "http://www.adicon.com.cn/GetByteReport")
    @ResponseWrapper(localName = "GetByteReportResponse", targetNamespace = "http://www.adicon.com.cn/", className = "cn.com.adicon.GetByteReportResponse")
    public byte[] getByteReport(
            @WebParam(name = "Id", targetNamespace = "http://www.adicon.com.cn/")
            String id,
            @WebParam(name = "key", targetNamespace = "http://www.adicon.com.cn/")
            String key
    );



    /**
     * 获取所有的标本列表。Key＝有效授权码，BeginDateTime＝起始时间， EndDateTime＝结束时间，TypeDateTime＝1=按采集时间统计，2＝按报告时间统计；AgainFlag:2=下载所有标本（包括已下载），0＝只下载未下载的标本
     */
    @WebResult(name = "GetAllSampleListResult", targetNamespace = "http://www.adicon.com.cn/")
    @RequestWrapper(localName = "GetAllSampleList", targetNamespace = "http://www.adicon.com.cn/", className = "cn.com.adicon.GetAllSampleList")
    @WebMethod(operationName = "GetAllSampleList", action = "http://www.adicon.com.cn/GetAllSampleList")
    @ResponseWrapper(localName = "GetAllSampleListResponse", targetNamespace = "http://www.adicon.com.cn/", className = "cn.com.adicon.GetAllSampleListResponse")
    public String getAllSampleList(
        @WebParam(name = "Key", targetNamespace = "http://www.adicon.com.cn/")
        String key,
        @WebParam(name = "BeginDateTime", targetNamespace = "http://www.adicon.com.cn/")
        String beginDateTime,
        @WebParam(name = "EndDateTime", targetNamespace = "http://www.adicon.com.cn/")
        String endDateTime,
        @WebParam(name = "TypeDateTime", targetNamespace = "http://www.adicon.com.cn/")
        String typeDateTime,
        @WebParam(name = "AgainFlag", targetNamespace = "http://www.adicon.com.cn/")
        String againFlag
    );

    /**
     * 状态回调：Key＝有效授权码，AdiconBarcode＝艾迪康12位条码。
     */
    @WebResult(name = "SetSampleDownFlagByAdiconBarocdeResult", targetNamespace = "http://www.adicon.com.cn/")
    @RequestWrapper(localName = "SetSampleDownFlagByAdiconBarocde", targetNamespace = "http://www.adicon.com.cn/", className = "cn.com.adicon.SetSampleDownFlagByAdiconBarocde")
    @WebMethod(operationName = "SetSampleDownFlagByAdiconBarocde", action = "http://www.adicon.com.cn/SetSampleDownFlagByAdiconBarocde")
    @ResponseWrapper(localName = "SetSampleDownFlagByAdiconBarocdeResponse", targetNamespace = "http://www.adicon.com.cn/", className = "cn.com.adicon.SetSampleDownFlagByAdiconBarocdeResponse")
    public String setSampleDownFlagByAdiconBarocde(
        @WebParam(name = "Key", targetNamespace = "http://www.adicon.com.cn/")
        String key,
        @WebParam(name = "AdiconBarcode", targetNamespace = "http://www.adicon.com.cn/")
        String adiconBarcode,
        @WebParam(name = "ReportType", targetNamespace = "http://www.adicon.com.cn/")
        String reportType
    );

    /**
     * 通过艾迪康条码获取唐筛标本图片信息（仅对济南、北京和天津的webservice有效，其他点无效）。Key＝有效授权码，AdiconBarcode=要查询的艾迪康条码号,ReportType=报告类型，请输入：唐筛，以验证你确实要获取唐筛信息
     */
    @WebResult(name = "GetTsscPicByAdiconBarcodeResult", targetNamespace = "http://www.adicon.com.cn/")
    @RequestWrapper(localName = "GetTsscPicByAdiconBarcode", targetNamespace = "http://www.adicon.com.cn/", className = "cn.com.adicon.GetTsscPicByAdiconBarcode")
    @WebMethod(operationName = "GetTsscPicByAdiconBarcode", action = "http://www.adicon.com.cn/GetTsscPicByAdiconBarcode")
    @ResponseWrapper(localName = "GetTsscPicByAdiconBarcodeResponse", targetNamespace = "http://www.adicon.com.cn/", className = "cn.com.adicon.GetTsscPicByAdiconBarcodeResponse")
    public byte[] getTsscPicByAdiconBarcode(
        @WebParam(name = "Key", targetNamespace = "http://www.adicon.com.cn/")
        String key,
        @WebParam(name = "AdiconBarcode", targetNamespace = "http://www.adicon.com.cn/")
        String adiconBarcode,
        @WebParam(name = "ReportType", targetNamespace = "http://www.adicon.com.cn/")
        String reportType
    );

    /**
     * 根据艾迪康条码查询。AdiconBarcode＝艾迪康12位条码,返回二进制报告单（假如有多张报告单，将合并成一张）
     */
    @WebResult(name = "GetSearchByteSampleResult", targetNamespace = "http://www.adicon.com.cn/")
    @RequestWrapper(localName = "GetSearchByteSample", targetNamespace = "http://www.adicon.com.cn/", className = "cn.com.adicon.GetSearchByteSample")
    @WebMethod(operationName = "GetSearchByteSample", action = "http://www.adicon.com.cn/GetSearchByteSample")
    @ResponseWrapper(localName = "GetSearchByteSampleResponse", targetNamespace = "http://www.adicon.com.cn/", className = "cn.com.adicon.GetSearchByteSampleResponse")
    public byte[] getSearchByteSample(
        @WebParam(name = "AdiconBarcode", targetNamespace = "http://www.adicon.com.cn/")
        String adiconBarcode,
        @WebParam(name = "Key", targetNamespace = "http://www.adicon.com.cn/")
        String key
    );

    /**
     * 根据艾迪康条码查询标本处理过程,AdiconBarcode＝艾迪康12位条码
     */
    @WebResult(name = "GetSampleProcessResult", targetNamespace = "http://www.adicon.com.cn/")
    @RequestWrapper(localName = "GetSampleProcess", targetNamespace = "http://www.adicon.com.cn/", className = "cn.com.adicon.GetSampleProcess")
    @WebMethod(operationName = "GetSampleProcess", action = "http://www.adicon.com.cn/GetSampleProcess")
    @ResponseWrapper(localName = "GetSampleProcessResponse", targetNamespace = "http://www.adicon.com.cn/", className = "cn.com.adicon.GetSampleProcessResponse")
    public String getSampleProcess(
        @WebParam(name = "AdiconBarcode", targetNamespace = "http://www.adicon.com.cn/")
        String adiconBarcode,
        @WebParam(name = "Key", targetNamespace = "http://www.adicon.com.cn/")
        String key
    );

    /**
     * 状态回调：Key＝有效授权码，AdiconRepno＝艾迪康生成的内部下载流水号。
     */
    @WebResult(name = "SetSampleDownFlagByByAdiconRepnoResult", targetNamespace = "http://www.adicon.com.cn/")
    @RequestWrapper(localName = "SetSampleDownFlagByByAdiconRepno", targetNamespace = "http://www.adicon.com.cn/", className = "cn.com.adicon.SetSampleDownFlagByByAdiconRepno")
    @WebMethod(operationName = "SetSampleDownFlagByByAdiconRepno", action = "http://www.adicon.com.cn/SetSampleDownFlagByByAdiconRepno")
    @ResponseWrapper(localName = "SetSampleDownFlagByByAdiconRepnoResponse", targetNamespace = "http://www.adicon.com.cn/", className = "cn.com.adicon.SetSampleDownFlagByByAdiconRepnoResponse")
    public String setSampleDownFlagByByAdiconRepno(
        @WebParam(name = "Key", targetNamespace = "http://www.adicon.com.cn/")
        String key,
        @WebParam(name = "AdiconRepno", targetNamespace = "http://www.adicon.com.cn/")
        String adiconRepno,
        @WebParam(name = "ReportType", targetNamespace = "http://www.adicon.com.cn/")
        String reportType
    );

    /**
     * 根据艾迪康条码获取标本检测结果或诊断结果。AdiconBarcode＝艾迪康12位条码
     */
    @WebResult(name = "GetJSONReportItemListByAdiconBarocdeResult", targetNamespace = "http://www.adicon.com.cn/")
    @RequestWrapper(localName = "GetJSONReportItemListByAdiconBarocde", targetNamespace = "http://www.adicon.com.cn/", className = "cn.com.adicon.GetJSONReportItemListByAdiconBarocde")
    @WebMethod(operationName = "GetJSONReportItemListByAdiconBarocde", action = "http://www.adicon.com.cn/GetJSONReportItemListByAdiconBarocde")
    @ResponseWrapper(localName = "GetJSONReportItemListByAdiconBarocdeResponse", targetNamespace = "http://www.adicon.com.cn/", className = "cn.com.adicon.GetJSONReportItemListByAdiconBarocdeResponse")
    public String getJSONReportItemListByAdiconBarocde(
        @WebParam(name = "AdiconBarcode", targetNamespace = "http://www.adicon.com.cn/")
        String adiconBarcode,
        @WebParam(name = "Key", targetNamespace = "http://www.adicon.com.cn/")
        String key
    );

    /**
     * 获取唐筛标本信息（仅对济南、北京和天津的webservice有效，其他点无效）。Key＝有效授权码，CustomerCode=要查询客户的代号（输入All，表示所有客户）,BeginDateTime＝起始时间， EndDateTime＝结束时间，TypeDateTime：1=按采集时间统计，2＝按测定时间统计；ReportType=报告类型，请输入：唐筛，以验证你确实要获取唐筛信息
     */
    @WebResult(name = "GetTsscInfoResult", targetNamespace = "http://www.adicon.com.cn/")
    @RequestWrapper(localName = "GetTsscInfo", targetNamespace = "http://www.adicon.com.cn/", className = "cn.com.adicon.GetTsscInfo")
    @WebMethod(operationName = "GetTsscInfo", action = "http://www.adicon.com.cn/GetTsscInfo")
    @ResponseWrapper(localName = "GetTsscInfoResponse", targetNamespace = "http://www.adicon.com.cn/", className = "cn.com.adicon.GetTsscInfoResponse")
    public String getTsscInfo(
        @WebParam(name = "Key", targetNamespace = "http://www.adicon.com.cn/")
        String key,
        @WebParam(name = "CustomerCode", targetNamespace = "http://www.adicon.com.cn/")
        String customerCode,
        @WebParam(name = "BeginDateTime", targetNamespace = "http://www.adicon.com.cn/")
        String beginDateTime,
        @WebParam(name = "EndDateTime", targetNamespace = "http://www.adicon.com.cn/")
        String endDateTime,
        @WebParam(name = "TypeDateTime", targetNamespace = "http://www.adicon.com.cn/")
        String typeDateTime,
        @WebParam(name = "ReportType", targetNamespace = "http://www.adicon.com.cn/")
        String reportType
    );

    /**
     * 根据艾迪康条码判断报告单是否检测完成
     */
    @WebResult(name = "ExistsReportResult", targetNamespace = "http://www.adicon.com.cn/")
    @RequestWrapper(localName = "ExistsReport", targetNamespace = "http://www.adicon.com.cn/", className = "cn.com.adicon.ExistsReport")
    @WebMethod(operationName = "ExistsReport", action = "http://www.adicon.com.cn/ExistsReport")
    @ResponseWrapper(localName = "ExistsReportResponse", targetNamespace = "http://www.adicon.com.cn/", className = "cn.com.adicon.ExistsReportResponse")
    public String existsReport(
        @WebParam(name = "AdiconBarcode", targetNamespace = "http://www.adicon.com.cn/")
        String adiconBarcode,
        @WebParam(name = "Key", targetNamespace = "http://www.adicon.com.cn/")
        String key
    );

    /**
     * 返回标本数：Key＝有效授权码
     */
    @WebResult(name = "GetSampleCountResult", targetNamespace = "http://www.adicon.com.cn/")
    @RequestWrapper(localName = "GetSampleCount", targetNamespace = "http://www.adicon.com.cn/", className = "cn.com.adicon.GetSampleCount")
    @WebMethod(operationName = "GetSampleCount", action = "http://www.adicon.com.cn/GetSampleCount")
    @ResponseWrapper(localName = "GetSampleCountResponse", targetNamespace = "http://www.adicon.com.cn/", className = "cn.com.adicon.GetSampleCountResponse")
    public String getSampleCount(
        @WebParam(name = "key", targetNamespace = "http://www.adicon.com.cn/")
        String key,
        @WebParam(name = "BeginDateTime", targetNamespace = "http://www.adicon.com.cn/")
        String beginDateTime,
        @WebParam(name = "EndDateTime", targetNamespace = "http://www.adicon.com.cn/")
        String endDateTime
    );

    /**
     * 病理和TCT的P图片，参数说明：barCode=中心条码 finterid=主键,PicType=图片类别：tct or 病理， CurrentRecord=取哪张图片
     */
    @WebResult(name = "GetBLTCTPicByKeyIdResult", targetNamespace = "http://www.adicon.com.cn/")
    @RequestWrapper(localName = "GetBLTCTPicByKeyId", targetNamespace = "http://www.adicon.com.cn/", className = "cn.com.adicon.GetBLTCTPicByKeyId")
    @WebMethod(operationName = "GetBLTCTPicByKeyId", action = "http://www.adicon.com.cn/GetBLTCTPicByKeyId")
    @ResponseWrapper(localName = "GetBLTCTPicByKeyIdResponse", targetNamespace = "http://www.adicon.com.cn/", className = "cn.com.adicon.GetBLTCTPicByKeyIdResponse")
    public String getBLTCTPicByKeyId(
        @WebParam(name = "Key", targetNamespace = "http://www.adicon.com.cn/")
        String key,
        @WebParam(name = "barCode", targetNamespace = "http://www.adicon.com.cn/")
        String barCode,
        @WebParam(name = "finterid", targetNamespace = "http://www.adicon.com.cn/")
        String finterid,
        @WebParam(name = "PicType", targetNamespace = "http://www.adicon.com.cn/")
        String picType,
        @WebParam(name = "CurrentRecord", targetNamespace = "http://www.adicon.com.cn/")
        int currentRecord
    );

    /**
     * 根据手机号或身份证号获取标本检测结果或诊断结果。OtherCode＝手机号或身份证号
     */
    @WebResult(name = "GetJSONReportItemListByOtherCodeResult", targetNamespace = "http://www.adicon.com.cn/")
    @RequestWrapper(localName = "GetJSONReportItemListByOtherCode", targetNamespace = "http://www.adicon.com.cn/", className = "cn.com.adicon.GetJSONReportItemListByOtherCode")
    @WebMethod(operationName = "GetJSONReportItemListByOtherCode", action = "http://www.adicon.com.cn/GetJSONReportItemListByOtherCode")
    @ResponseWrapper(localName = "GetJSONReportItemListByOtherCodeResponse", targetNamespace = "http://www.adicon.com.cn/", className = "cn.com.adicon.GetJSONReportItemListByOtherCodeResponse")
    public String getJSONReportItemListByOtherCode(
        @WebParam(name = "OtherCode", targetNamespace = "http://www.adicon.com.cn/")
        String otherCode,
        @WebParam(name = "Key", targetNamespace = "http://www.adicon.com.cn/")
        String key,
        @WebParam(name = "datetime", targetNamespace = "http://www.adicon.com.cn/")
        String datetime
    );

    /**
     * 根据艾迪康条码获取标本检测结果或诊断结果。Key＝有效授权码，AdiconBarcode＝艾迪康12位条码。
     */
    @WebResult(name = "GetReportItemListByAdiconBarocdeResult", targetNamespace = "http://www.adicon.com.cn/")
    @RequestWrapper(localName = "GetReportItemListByAdiconBarocde", targetNamespace = "http://www.adicon.com.cn/", className = "cn.com.adicon.GetReportItemListByAdiconBarocde")
    @WebMethod(operationName = "GetReportItemListByAdiconBarocde", action = "http://www.adicon.com.cn/GetReportItemListByAdiconBarocde")
    @ResponseWrapper(localName = "GetReportItemListByAdiconBarocdeResponse", targetNamespace = "http://www.adicon.com.cn/", className = "cn.com.adicon.GetReportItemListByAdiconBarocdeResponse")
    public String getReportItemListByAdiconBarocde(
        @WebParam(name = "Key", targetNamespace = "http://www.adicon.com.cn/")
        String key,
        @WebParam(name = "AdiconBarcode", targetNamespace = "http://www.adicon.com.cn/")
        String adiconBarcode,
        @WebParam(name = "ReportType", targetNamespace = "http://www.adicon.com.cn/")
        String reportType
    );

    /**
     * 根据手机号码或身份证号查询。AdiconBarcode＝手机号码或身份证号,返回二进制报告单（假如有多张报告单，将合并成一张）
     */
    @WebResult(name = "GetSearchByteSampleByOtherResult", targetNamespace = "http://www.adicon.com.cn/")
    @RequestWrapper(localName = "GetSearchByteSampleByOther", targetNamespace = "http://www.adicon.com.cn/", className = "cn.com.adicon.GetSearchByteSampleByOther")
    @WebMethod(operationName = "GetSearchByteSampleByOther", action = "http://www.adicon.com.cn/GetSearchByteSampleByOther")
    @ResponseWrapper(localName = "GetSearchByteSampleByOtherResponse", targetNamespace = "http://www.adicon.com.cn/", className = "cn.com.adicon.GetSearchByteSampleByOtherResponse")
    public byte[] getSearchByteSampleByOther(
        @WebParam(name = "AdiconBarcode", targetNamespace = "http://www.adicon.com.cn/")
        String adiconBarcode,
        @WebParam(name = "Key", targetNamespace = "http://www.adicon.com.cn/")
        String key
    );

    /**
     * 根据艾迪康报告单下载流水号获取标本检测结果。Key＝有效授权码，AdiconRepno＝艾迪康生成的内部下载流水号。此方法可下载单标本的完整报告单。
     */
    @WebResult(name = "GetReportItemListByAdiconRepnoResult", targetNamespace = "http://www.adicon.com.cn/")
    @RequestWrapper(localName = "GetReportItemListByAdiconRepno", targetNamespace = "http://www.adicon.com.cn/", className = "cn.com.adicon.GetReportItemListByAdiconRepno")
    @WebMethod(operationName = "GetReportItemListByAdiconRepno", action = "http://www.adicon.com.cn/GetReportItemListByAdiconRepno")
    @ResponseWrapper(localName = "GetReportItemListByAdiconRepnoResponse", targetNamespace = "http://www.adicon.com.cn/", className = "cn.com.adicon.GetReportItemListByAdiconRepnoResponse")
    public String getReportItemListByAdiconRepno(
        @WebParam(name = "Key", targetNamespace = "http://www.adicon.com.cn/")
        String key,
        @WebParam(name = "AdiconRepno", targetNamespace = "http://www.adicon.com.cn/")
        String adiconRepno,
        @WebParam(name = "ReportType", targetNamespace = "http://www.adicon.com.cn/")
        String reportType
    );

    /**
     * 用户验证获得授权码
     */
    @WebResult(name = "LoginResult", targetNamespace = "http://www.adicon.com.cn/")
    @RequestWrapper(localName = "Login", targetNamespace = "http://www.adicon.com.cn/", className = "cn.com.adicon.Login")
    @WebMethod(operationName = "Login", action = "http://www.adicon.com.cn/Login")
    @ResponseWrapper(localName = "LoginResponse", targetNamespace = "http://www.adicon.com.cn/", className = "cn.com.adicon.LoginResponse")
    public String login(
        @WebParam(name = "logid", targetNamespace = "http://www.adicon.com.cn/")
        String logid,
        @WebParam(name = "password", targetNamespace = "http://www.adicon.com.cn/")
        String password
    );
}
