package com.center.medical.center.common.service;

import com.center.medical.center.common.bean.model.AdiconWebServiceHttpGet;
import com.center.medical.center.common.bean.model.AdiconWebServiceHttpPost;
import com.center.medical.center.common.bean.model.AdiconWebServiceSoap;
import com.center.medical.center.common.constant.CenterConstant;
import com.center.medical.center.common.util.PropertyUtil;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import java.net.MalformedURLException;
import java.net.URL;

/**
 * ADICON报告单对外服务接口
 *
 * This class was generated by Apache CXF 3.1.9
 * 2017-01-12T17:38:48.662+08:00
 * Generated source version: 3.1.9
 * 
 */
@WebServiceClient(name = "AdiconWebService", 
					//注解与下面的代码作用重复，这里要求可配置，故舍弃注解
                  //wsdlLocation = "http://124.133.35.146:8889/ADReportWebService.asmx?WSDL",
                  targetNamespace = "http://www.adicon.com.cn/") 
public class AdiconWebService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://www.adicon.com.cn/", "AdiconWebService");
    public final static QName AdiconWebServiceHttpPost = new QName("http://www.adicon.com.cn/", "AdiconWebServiceHttpPost");
    public final static QName AdiconWebServiceHttpGet = new QName("http://www.adicon.com.cn/", "AdiconWebServiceHttpGet");
    public final static QName AdiconWebServiceSoap12 = new QName("http://www.adicon.com.cn/", "AdiconWebServiceSoap12");
    public final static QName AdiconWebServiceSoap = new QName("http://www.adicon.com.cn/", "AdiconWebServiceSoap");
    static {
        URL url = null;
        try {
            //潍坊使用山东艾迪康，其他使用青岛艾迪康
            String property = PropertyUtil.getProperty("spring.profiles.active");
            url = new URL(property.contains(CenterConstant.WF)?"http://124.133.35.146:8889/ADReportWebService.asmx?WSDL":
                    property.contains(CenterConstant.BZ)?"http://124.193.207.82/BJWebService/ADReportWebService.asmx?WSDL"
                            :"http://qdreport.adicon.com.cn:8889/ADReportWebService.asmx?WSDL");
//        	url = new URL("http://124.193.207.82/BJWebService/ADReportWebService.asmx?WSDL");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(AdiconWebService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://124.133.35.146:8889/ADReportWebService.asmx?WSDL");
        }
        WSDL_LOCATION = url;
    }

    public AdiconWebService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public AdiconWebService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public AdiconWebService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public AdiconWebService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE);
    }

    public AdiconWebService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE);
    }

    public AdiconWebService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName);
    }    




    /**
     *
     * @return
     *     returns AdiconWebServiceHttpPost
     */
    @WebEndpoint(name = "AdiconWebServiceHttpPost")
    public AdiconWebServiceHttpPost getAdiconWebServiceHttpPost() {
        return super.getPort(AdiconWebServiceHttpPost, AdiconWebServiceHttpPost.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns AdiconWebServiceHttpPost
     */
    @WebEndpoint(name = "AdiconWebServiceHttpPost")
    public AdiconWebServiceHttpPost getAdiconWebServiceHttpPost(WebServiceFeature... features) {
        return super.getPort(AdiconWebServiceHttpPost, AdiconWebServiceHttpPost.class, features);
    }


    /**
     *
     * @return
     *     returns AdiconWebServiceHttpGet
     */
    @WebEndpoint(name = "AdiconWebServiceHttpGet")
    public AdiconWebServiceHttpGet getAdiconWebServiceHttpGet() {
        return super.getPort(AdiconWebServiceHttpGet, AdiconWebServiceHttpGet.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns AdiconWebServiceHttpGet
     */
    @WebEndpoint(name = "AdiconWebServiceHttpGet")
    public AdiconWebServiceHttpGet getAdiconWebServiceHttpGet(WebServiceFeature... features) {
        return super.getPort(AdiconWebServiceHttpGet, AdiconWebServiceHttpGet.class, features);
    }


    /**
     *
     * @return
     *     returns AdiconWebServiceSoap
     */
    @WebEndpoint(name = "AdiconWebServiceSoap12")
    public AdiconWebServiceSoap getAdiconWebServiceSoap12() {
        return super.getPort(AdiconWebServiceSoap12, AdiconWebServiceSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns AdiconWebServiceSoap
     */
    @WebEndpoint(name = "AdiconWebServiceSoap12")
    public AdiconWebServiceSoap getAdiconWebServiceSoap12(WebServiceFeature... features) {
        return super.getPort(AdiconWebServiceSoap12, AdiconWebServiceSoap.class, features);
    }


    /**
     *
     * @return
     *     returns AdiconWebServiceSoap
     */
    @WebEndpoint(name = "AdiconWebServiceSoap")
    public AdiconWebServiceSoap getAdiconWebServiceSoap() {
        return super.getPort(AdiconWebServiceSoap, AdiconWebServiceSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns AdiconWebServiceSoap
     */
    @WebEndpoint(name = "AdiconWebServiceSoap")
    public AdiconWebServiceSoap getAdiconWebServiceSoap(WebServiceFeature... features) {
        return super.getPort(AdiconWebServiceSoap, AdiconWebServiceSoap.class, features);
    }

}
